CREATE SCHEMA IF NOT EXISTS java2module
  DEFAULT CHARACTER SET utf8;
USE java2module;


CREATE TABLE IF NOT EXISTS developers (
  ID         INT         NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME  VARCHAR(50) NOT NULL
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS customers (
  ID   INT         NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS companies (
  ID   INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL
)
  ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS projects (
  ID   INT          NOT NULL PRIMARY KEY  AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS skills (
  ID   INT         NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS developers_skills (
  ID_DEV   INT NOT NULL ,
  ID_SKILL INT NOT NULL ,
  PRIMARY KEY (ID_DEV, ID_SKILL),
  FOREIGN KEY (ID_DEV) REFERENCES developers (ID),
  FOREIGN KEY (ID_SKILL) REFERENCES skills (ID)
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS projects_developers(
  ID_PROJECT INT NOT NULL ,
  ID_DEV     INT NOT NULL ,
  PRIMARY KEY (ID_PROJECT, ID_DEV),
  FOREIGN KEY (ID_PROJECT) REFERENCES projects (ID),
  FOREIGN KEY (ID_DEV) REFERENCES developers (ID)
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS companies_developers (
  ID_COMP INT NOT NULL ,
  ID_DEV  INT NOT NULL ,
  PRIMARY KEY (ID_COMP, ID_DEV),
  FOREIGN KEY (ID_COMP) REFERENCES companies (ID),
  FOREIGN KEY (ID_DEV) REFERENCES developers (ID)
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS customers_projects (
  ID_CUST    INT NOT NULL ,
  ID_PROJECT INT NOT NULL ,
  PRIMARY KEY (ID_CUST, ID_PROJECT),
  FOREIGN KEY (ID_CUST) REFERENCES customers (ID),
  FOREIGN KEY (ID_PROJECT) REFERENCES projects (ID)
)
  ENGINE = InnoDB;