-- MySQL Script generated by MySQL Workbench
-- 02/19/17 15:18:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema homework1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema homework1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homework1` DEFAULT CHARACTER SET utf8 ;
USE `homework1` ;

-- -----------------------------------------------------
-- Table `homework1`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework1`.`companies` (
  `id_company` INT NOT NULL AUTO_INCREMENT,
  `name_company` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_company`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework1`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework1`.`customers` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `name_customer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_customer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework1`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework1`.`projects` (
  `id_project` INT NOT NULL AUTO_INCREMENT,
  `name_project` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_project`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework1`.`developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework1`.`developers` (
  `id_developers` INT NOT NULL AUTO_INCREMENT,
  `name_dev` VARCHAR(45) NOT NULL,
  `surname_dev` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_developers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework1`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework1`.`skills` (
  `id_skill` INT NOT NULL AUTO_INCREMENT,
  `name_skill` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_skill`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework1`.`dev_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework1`.`dev_skills` (
  `id_dev` INT NOT NULL,
  `id_skill` INT NOT NULL,
  PRIMARY KEY (`id_skill`, `id_dev`),
  INDEX `1_idx` (`id_dev` ASC),
  CONSTRAINT `1`
    FOREIGN KEY (`id_dev`)
    REFERENCES `homework1`.`developers` (`id_developers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `2`
    FOREIGN KEY (`id_skill`)
    REFERENCES `homework1`.`skills` (`id_skill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework1`.`project_devs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework1`.`project_devs` (
  `id_project` INT NOT NULL,
  `id_dev` INT NOT NULL,
  PRIMARY KEY (`id_project`, `id_dev`),
  INDEX `id_dev_idx` (`id_dev` ASC),
  CONSTRAINT `id_project`
    FOREIGN KEY (`id_project`)
    REFERENCES `homework1`.`projects` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_dev`
    FOREIGN KEY (`id_dev`)
    REFERENCES `homework1`.`developers` (`id_developers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework1`.`comp_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework1`.`comp_project` (
  `id_project` INT NOT NULL,
  `id_comp` INT NOT NULL,
  PRIMARY KEY (`id_project`, `id_comp`),
  INDEX `fk_id_comp_idx` (`id_comp` ASC),
  CONSTRAINT `fk_id_project`
    FOREIGN KEY (`id_project`)
    REFERENCES `homework1`.`projects` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_comp`
    FOREIGN KEY (`id_comp`)
    REFERENCES `homework1`.`companies` (`id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework1`.`customers_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework1`.`customers_project` (
  `id_cust` INT NOT NULL,
  `id_proj` INT NOT NULL,
  PRIMARY KEY (`id_cust`, `id_proj`),
  INDEX `fk_customers_project_projects1_idx` (`id_proj` ASC),
  CONSTRAINT `fk_customers_project_customers1`
    FOREIGN KEY (`id_cust`)
    REFERENCES `homework1`.`customers` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_project_projects1`
    FOREIGN KEY (`id_proj`)
    REFERENCES `homework1`.`projects` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework1`.`companies_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework1`.`companies_customers` (
  `id_company` INT NOT NULL,
  `id_customer` INT NOT NULL,
  PRIMARY KEY (`id_company`, `id_customer`),
  INDEX `fk_companies_customers_customers1_idx` (`id_customer` ASC),
  CONSTRAINT `fk_companies_customers_companies1`
    FOREIGN KEY (`id_company`)
    REFERENCES `homework1`.`companies` (`id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_customers_customers1`
    FOREIGN KEY (`id_customer`)
    REFERENCES `homework1`.`customers` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework1`.`company_devs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework1`.`company_devs` (
  `id_company` INT NOT NULL,
  `id_dev` INT NOT NULL,
  PRIMARY KEY (`id_company`, `id_dev`),
  INDEX `fk_company_devs_developers1_idx` (`id_dev` ASC),
  CONSTRAINT `fk_company_devs_companies1`
    FOREIGN KEY (`id_company`)
    REFERENCES `homework1`.`companies` (`id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_devs_developers1`
    FOREIGN KEY (`id_dev`)
    REFERENCES `homework1`.`developers` (`id_developers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
